import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx (App Router)
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={geistSans.className}>
      <body className="bg-gradient-to-b dark:from-slate-950 dark:to-indigo-950 from-slate-200 to-slate-50 min-h-screen md:mx-32 my-8">
            {children}</body>
    </html>
  )
}
